# Generated by Django 6.0.7 on 2026-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vault",
            name="webauthn_credential_public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
