# Generated by Django 6.0.7 on 2026-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0002_vault_webauthn_credential_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password_strength",
            field=models.IntegerField(
                blank=True,
                help_text="Password strength score (0-100). Null if not evaluated.",
                null=True,
            ),
        ),
    ]
