# Generated by Django 6.0.7 on 2026-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0003_account_password_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of the plaintext password. Used for detecting reused passwords.",
                max_length=64,
                null=True,
            ),
        ),
    ]
