# Generated by Django 6.0.7 on 2026-07-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0004_account_password_fingerprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="password_fingerprint",
        ),
    ]
